//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeneyOnayTBL
    {
        public int DeneyOnayID { get; set; }
        public Nullable<int> DeneyID { get; set; }
        public Nullable<System.DateTime> DeneyOnayTarih { get; set; }
        public Nullable<bool> DeneyOnayDurumu { get; set; }
    
        public virtual DeneylerTBL DeneylerTBL { get; set; }
    }
}
