//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyurularTBL
    {
        public int DuyuruID { get; set; }
        public string DuyuruBaşlık { get; set; }
        public string Duyruİçerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> DuyuruDurum { get; set; }
        public Nullable<int> DuyuruEkleyenPersonelID { get; set; }
    
        public virtual PersonellerTBL PersonellerTBL { get; set; }
    }
}
