//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratuvarlarTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaboratuvarlarTBL()
        {
            this.FaturalarTBL = new HashSet<FaturalarTBL>();
            this.NumunelerTBL = new HashSet<NumunelerTBL>();
            this.PersonellerTBL = new HashSet<PersonellerTBL>();
            this.RaporlarTBL = new HashSet<RaporlarTBL>();
        }
    
        public int LabID { get; set; }
        public string LabKodu { get; set; }
        public Nullable<byte> LabTurID { get; set; }
        public Nullable<bool> LabDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturalarTBL> FaturalarTBL { get; set; }
        public virtual LabTurTBL LabTurTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumunelerTBL> NumunelerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonellerTBL> PersonellerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaporlarTBL> RaporlarTBL { get; set; }
    }
}
