//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratuvarDBEntities2 : DbContext
    {
        public LaboratuvarDBEntities2()
            : base("name=LaboratuvarDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeneylerTBL> DeneylerTBL { get; set; }
        public virtual DbSet<DeneyOnayTBL> DeneyOnayTBL { get; set; }
        public virtual DbSet<DeneyPersonelIslemTBL> DeneyPersonelIslemTBL { get; set; }
        public virtual DbSet<DeneyTurTBL> DeneyTurTBL { get; set; }
        public virtual DbSet<DuyurularTBL> DuyurularTBL { get; set; }
        public virtual DbSet<FaturalarTBL> FaturalarTBL { get; set; }
        public virtual DbSet<FaturaTurTBL> FaturaTurTBL { get; set; }
        public virtual DbSet<IzınTBL> IzınTBL { get; set; }
        public virtual DbSet<LaboratuvarlarTBL> LaboratuvarlarTBL { get; set; }
        public virtual DbSet<LabTurTBL> LabTurTBL { get; set; }
        public virtual DbSet<MalzemelerTBL> MalzemelerTBL { get; set; }
        public virtual DbSet<MesajlarTBL> MesajlarTBL { get; set; }
        public virtual DbSet<NumunelerTBL> NumunelerTBL { get; set; }
        public virtual DbSet<NumuneTurTBL> NumuneTurTBL { get; set; }
        public virtual DbSet<OdenenFaturaTBL> OdenenFaturaTBL { get; set; }
        public virtual DbSet<OnaylananRaporTBL> OnaylananRaporTBL { get; set; }
        public virtual DbSet<PersonellerTBL> PersonellerTBL { get; set; }
        public virtual DbSet<PersonelTurTBL> PersonelTurTBL { get; set; }
        public virtual DbSet<RaporlarTBL> RaporlarTBL { get; set; }
        public virtual DbSet<RaporTurTBL> RaporTurTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
