//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumunelerTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NumunelerTBL()
        {
            this.DeneylerTBL = new HashSet<DeneylerTBL>();
            this.FaturalarTBL = new HashSet<FaturalarTBL>();
            this.RaporlarTBL = new HashSet<RaporlarTBL>();
        }
    
        public int NumuneID { get; set; }
        public string NumuneAd { get; set; }
        public string NumuneSoyad { get; set; }
        public Nullable<byte> NumuneTürID { get; set; }
        public Nullable<int> NumuneAlanPersonelID { get; set; }
        public Nullable<int> LabID { get; set; }
        public Nullable<byte> LabTurID { get; set; }
        public Nullable<System.DateTime> NumuneAlinisTarih { get; set; }
        public Nullable<decimal> NumuneMiktar { get; set; }
        public Nullable<int> NumuneAdet { get; set; }
        public string Mail { get; set; }
        public string NumSifre1 { get; set; }
        public string NumSifre2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeneylerTBL> DeneylerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturalarTBL> FaturalarTBL { get; set; }
        public virtual LaboratuvarlarTBL LaboratuvarlarTBL { get; set; }
        public virtual LabTurTBL LabTurTBL { get; set; }
        public virtual NumuneTurTBL NumuneTurTBL { get; set; }
        public virtual PersonellerTBL PersonellerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaporlarTBL> RaporlarTBL { get; set; }
    }
}
