//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdenenFaturaTBL
    {
        public int ÖdenenFaturaID { get; set; }
        public Nullable<int> FaturaID { get; set; }
        public Nullable<System.DateTime> OdenmeTarih { get; set; }
        public Nullable<bool> FaturaOdenmeDurum { get; set; }
        public Nullable<int> IslemYapanPersonel { get; set; }
    
        public virtual FaturalarTBL FaturalarTBL { get; set; }
        public virtual PersonellerTBL PersonellerTBL { get; set; }
    }
}
