//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonellerTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonellerTBL()
        {
            this.DeneylerTBL = new HashSet<DeneylerTBL>();
            this.DeneyPersonelIslemTBL = new HashSet<DeneyPersonelIslemTBL>();
            this.DuyurularTBL = new HashSet<DuyurularTBL>();
            this.FaturalarTBL = new HashSet<FaturalarTBL>();
            this.IzınTBL = new HashSet<IzınTBL>();
            this.NumunelerTBL = new HashSet<NumunelerTBL>();
            this.RaporlarTBL = new HashSet<RaporlarTBL>();
            this.OdenenFaturaTBL = new HashSet<OdenenFaturaTBL>();
            this.OnaylananRaporTBL = new HashSet<OnaylananRaporTBL>();
        }
    
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string Mail { get; set; }
        public string KullanıcıAdi { get; set; }
        public string Sifre1 { get; set; }
        public string Sifre2 { get; set; }
        public Nullable<byte> PersonelTurID { get; set; }
        public Nullable<int> LabID { get; set; }
        public Nullable<bool> PersonelDurum { get; set; }
        public Nullable<bool> PersonelSilmeDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeneylerTBL> DeneylerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeneyPersonelIslemTBL> DeneyPersonelIslemTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuyurularTBL> DuyurularTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturalarTBL> FaturalarTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzınTBL> IzınTBL { get; set; }
        public virtual LaboratuvarlarTBL LaboratuvarlarTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumunelerTBL> NumunelerTBL { get; set; }
        public virtual PersonelTurTBL PersonelTurTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaporlarTBL> RaporlarTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdenenFaturaTBL> OdenenFaturaTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnaylananRaporTBL> OnaylananRaporTBL { get; set; }
    }
}
