//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MneLabMVC.Models.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaporlarTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaporlarTBL()
        {
            this.OnaylananRaporTBL = new HashSet<OnaylananRaporTBL>();
        }
    
        public int RaporID { get; set; }
        public Nullable<int> LabID { get; set; }
        public Nullable<int> NumuneID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string RaporNo { get; set; }
        public Nullable<bool> RaporDurum { get; set; }
        public Nullable<System.DateTime> RaporDuzenTarih { get; set; }
        public Nullable<int> RaporTurID { get; set; }
    
        public virtual LaboratuvarlarTBL LaboratuvarlarTBL { get; set; }
        public virtual NumunelerTBL NumunelerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnaylananRaporTBL> OnaylananRaporTBL { get; set; }
        public virtual PersonellerTBL PersonellerTBL { get; set; }
        public virtual RaporTurTBL RaporTurTBL { get; set; }
    }
}
